manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/SixPiinGit
    - name: gpeye
      url-base: https://github.com/GPeye
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: hammerbeam-slideshow
      remote: gpeye
      revision: main 
    - name: zmk-a320-driver
      remote: zmkfirmware
      revision: main 
  self:
    path: boards
